//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruyenAtsukoiya
{


    public partial class Default
    {

        /// <summary>
        /// UCC_AllTruyenDataList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TruyenAtsukoiya.UCC_AllTruyenDataList UCC_AllTruyenDataList1;
    }
}
